# Generated by Django 3.0.6 on 2020-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='A9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20000)),
                ('Sanskrit', models.TextField(max_length=20000)),
                ('English', models.TextField(max_length=20000)),
            ],
        ),
    ]
